# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grpc_out.plantdisease_pb2 as plantdisease__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in plantdisease_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DiseaseClassifierStub(object):
    """The gRPC service for plant disease classification
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClassifyDisease = channel.unary_unary(
                '/plantdisease.DiseaseClassifier/ClassifyDisease',
                request_serializer=plantdisease__pb2.ClassifyRequest.SerializeToString,
                response_deserializer=plantdisease__pb2.ClassifyResponse.FromString,
                _registered_method=True)


class DiseaseClassifierServicer(object):
    """The gRPC service for plant disease classification
    """

    def ClassifyDisease(self, request, context):
        """The classify method accepts an image and returns the disease result
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiseaseClassifierServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClassifyDisease': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyDisease,
                    request_deserializer=plantdisease__pb2.ClassifyRequest.FromString,
                    response_serializer=plantdisease__pb2.ClassifyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'plantdisease.DiseaseClassifier', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('plantdisease.DiseaseClassifier', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DiseaseClassifier(object):
    """The gRPC service for plant disease classification
    """

    @staticmethod
    def ClassifyDisease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plantdisease.DiseaseClassifier/ClassifyDisease',
            plantdisease__pb2.ClassifyRequest.SerializeToString,
            plantdisease__pb2.ClassifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
